### ISSUE TITLE
[Win10] Control buttons disabled

### ISSUE THREAD

**Issue by alexander7567** [MediaBrowser/Emby.WindowsRT#78]
With Windows 10, the control buttons are greyed out when trying to pause/FF/RW a video. The only button that works is the back button. This issue exists with both offline and online content. This problem is only present in Windows 10.

![image](https://cloud.githubusercontent.com/assets/1144391/6973266/8f73cf2a-d957-11e4-9bae-896d43d55c0d.png)

**Comment by 7illusions** [comment]
Colsing - This was caused by an early build of Win10
